id: I43643BD3
legacy_id: P000705
ocr_import_info:
  bdrc_scan_id: W2PD20252
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T02:40:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:04:54.738616+00:00'
last_modified: 2022-09-03 19:07:45.336478
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2PD20252
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2PD20252
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མཁས་གྲུབ་ཀརྨ་ཆགས་མེད་ཀྱི་གསུང་འབུམ་ལས། ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: གནས་མདོ་ཀརྨ་ཆགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.889179293334193
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I2PD20750:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20750
      total_pages: 840
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD20750.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8800758072148924
    legacy_id: v004
  I2PD20749:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20749
      total_pages: 646
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD20749.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8579269208869851
    legacy_id: v003
  I2PD20752:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20752
      total_pages: 592
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2PD20752.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8991418477749799
    legacy_id: v006
  I2PD20747:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20747
      total_pages: 872
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD20747.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8961408746038549
    legacy_id: v001
  I2PD20754:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20754
      total_pages: 664
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2PD20754.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8729618783058555
    legacy_id: v008
  I2PD20755:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20755
      total_pages: 660
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2PD20755.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9062052618215358
    legacy_id: v009
  I2PD20748:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20748
      total_pages: 704
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD20748.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8599253655800146
    legacy_id: v002
  I2PD20753:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20753
      total_pages: 832
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2PD20753.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9188373507798431
    legacy_id: v007
  I2PD20751:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20751
      total_pages: 684
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD20751.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.901541766273818
    legacy_id: v005
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
