id: I43643BD3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T02:46:29+00:00'
last_modified: '2022-06-07T12:42:29.450288+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD20252
  title: མཁས་གྲུབ་ཀརྨ་ཆགས་མེད་ཀྱི་གསུང་འབུམ་ལས། ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    8F8C:
      image_group_id: I2PD20747
      title: ''
      total_pages: 872
      order: 1
      base_file: 8F8C.txt
    '2843':
      image_group_id: I2PD20748
      title: ''
      total_pages: 704
      order: 2
      base_file: 2843.txt
    6B1B:
      image_group_id: I2PD20749
      title: ''
      total_pages: 646
      order: 3
      base_file: 6B1B.txt
    B2FA:
      image_group_id: I2PD20750
      title: ''
      total_pages: 840
      order: 4
      base_file: B2FA.txt
    B354:
      image_group_id: I2PD20751
      title: ''
      total_pages: 684
      order: 5
      base_file: B354.txt
    E0E7:
      image_group_id: I2PD20752
      title: ''
      total_pages: 592
      order: 6
      base_file: E0E7.txt
    B530:
      image_group_id: I2PD20753
      title: ''
      total_pages: 832
      order: 7
      base_file: B530.txt
    BF06:
      image_group_id: I2PD20754
      title: ''
      total_pages: 664
      order: 8
      base_file: BF06.txt
    25DB:
      image_group_id: I2PD20755
      title: ''
      total_pages: 660
      order: 9
      base_file: 25DB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
