id: P000705
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-16 16:38:03.157401
source_metadata:
  id: bdr:W2PD20252
  title: མཁས་གྲུབ་ཀརྨ་ཆགས་མེད་ཀྱི་གསུང་འབུམ་ལས། ཉེར་མཁོ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    0065ab53622f45e88e5cd6c30494b794:
      image_group_id: I2PD20747
      title: ''
      volume_number: 1
      total_pages: 872
      base_file: v001.txt
    b5439820b1b84967873b901c7b725c69:
      image_group_id: I2PD20748
      title: ''
      volume_number: 2
      total_pages: 704
      base_file: v002.txt
    2f772cec7fd74323b73a24680d7f4474:
      image_group_id: I2PD20749
      title: ''
      volume_number: 3
      total_pages: 646
      base_file: v003.txt
    f4cd001c56cc44c48956adbb64000e16:
      image_group_id: I2PD20750
      title: ''
      volume_number: 4
      total_pages: 840
      base_file: v004.txt
    f920e1a397c54a8ab8a1f7d2b54b7edf:
      image_group_id: I2PD20751
      title: ''
      volume_number: 5
      total_pages: 684
      base_file: v005.txt
    90dc24b4db42490a8302d4b1f957b7b3:
      image_group_id: I2PD20752
      title: ''
      volume_number: 6
      total_pages: 592
      base_file: v006.txt
    4c9bbffed36d4b64a2f6b8242567872f:
      image_group_id: I2PD20753
      title: ''
      volume_number: 7
      total_pages: 832
      base_file: v007.txt
    59e2708879094beda5584507171759e3:
      image_group_id: I2PD20754
      title: ''
      volume_number: 8
      total_pages: 664
      base_file: v008.txt
    e82f9dfade814703a7cb120cd0321794:
      image_group_id: I2PD20755
      title: ''
      volume_number: 9
      total_pages: 660
      base_file: v009.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
